-- AlterTable
ALTER TABLE "Order" ADD COLUMN "packed" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN "fulfilled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN "paid" BOOLEAN NOT NULL DEFAULT false;
